### ISSUE TITLE
export messages json is 0 bytes

### ISSUE THREAD

**Issue by QuestioningEspecialy** [FossifyOrg/Messages#169] opened 2024-05-11 01:23 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 14 / GrapheneOS

### Affected device model

Google Pixel 6a

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. open app
2. gear icon
3. Export messages
4. leave name as is and both boxes (Export SMS & MMS) checked
5. OK
6. navigate to file from File Manager or desktop
7. notice its "0 bytes" file size

### Expected behavior

should be atleast a kilobyte, but probably over 300MB by now

### Actual behavior

its file size ain't even a byte 😐

### Additional information

n/a

**Comment by Aga-C** [comment] 2024-05-11 05:54
1. Just to be sure - have you checked if the file really has no data? Because it can be working, but for a some reason Android reports wrong file size.
2. Does it work when you check to export only SMS?
3. When exporting, do you see a toast message informing that the export has been successful?

**Comment by naveensingh** [comment] 2024-05-11 07:24
> Because it can be working, but for a some reason Android reports wrong file size.

This has happened to me too. The file size was correct when I checked using a file manager but it was 0 bytes only in the document file picker. https://github.com/FossifyOrg/General-Discussion/issues/120 will at least clear up the progress issue.

**Comment by Aga-C** [comment] 2024-05-11 14:09
> is there a quick way to check without temporarily installing a different messenger app? don't want duplicates in my primary messenger 🤷🏿‍♂️

You could open it as a text file in any file manager app. You can even open it on your desktop in Notepad. I was only interested if there's any data in a file because Android can report file size wrongly.

> but exporting MMS alone doesn't

If there's no data in a file, it sounds like it can be a similar problem as https://github.com/FossifyOrg/Messages/issues/6, but for some reason the app doesn't crash in your case. Maybe the same fix will help. In that issue, the author of the fix uploaded an APK file - you can check if it also addresses your problem.

**Comment by tom93** [comment] 2024-05-19 12:17
@QuestioningEspecialy I can't reproduce the new SecurityException (https://github.com/fossifyorg/messages/issues/6#issuecomment-2105940085). Have you tried stock Android, or only GrapheneOS? And which file picker are you using?
(I tested in an emulator running Android 14, device definition Pixel 6a, architecture x86_64 because the emulator didn't support arm64-v8a in my setup; command: `avdmanager create avd --name pixel_6a -k "system-images;android-34;default;x86_64" -d pixel_6a`)
I don't think the SecurityException is caused by my patch. Probably the patch is allowing the app to progress further and encounter the SecurityException. If you can [get the debug logs](https://github.com/FossifyOrg/Messages/issues/88#issuecomment-2006047401) it would probably be helpful.
Another thing to try (easy but only marginally useful) is to switch back to the official release and export just SMS, and then just MMS; hopefully one of them would be small enough for the export to progress, and either succeed or run into the same SecurityException (the aim is to pinpoint whether the SecurityException is caused by the debug release or something else).

**Comment by tom93** [comment] 2024-05-21 10:04
The file picker is the app that asks you to pick the destination folder. It opens after you tap "OK" in dialog for choosing what to export (SMS/MMS). You should be able to tell by the appearance whether it's a native file manager or Fossify File Manager.

I tested with Fossify File Manager as the file picker on Android (I had to run `pm hide com.android.documentsui` as root to avoid using the native file manager), but I still didn't get the SecurityException.

I can't find an easy way to run GrapheneOS in an emulator. Speaking for myself (since I'm not on the Fossify team), I think the GrapheneOS team should take a look at this and let us know whether it's a bug in GrapheneOS or the Fossify apps, because it's working fine on Android and I can't find an easy way to test on GrapheneOS. They should be able to reproduce the issue using the official release of Messages from GitHub or F-Droid; they'll just need to ensure that the export is small, otherwise they'll run into the issue you initially ran into (#6).

If you'd like to back up your messages soon, it might be possible to find a temporary workaround (e.g. use Android's [sharing API](https://developer.android.com/training/secure-file-sharing) to transfer the exported file to another app such as the file manager).

**Comment by s1nistr4** [comment] 2024-06-30 22:25
If I had a nickel for every time a FOSS messaging app messed up backup/restore, I'd have two nickels, which isn't a lot but it's weird that it happened twice (the other being QUIK sms)

**Comment by DaGeek247** [comment] 2024-07-06 22:28
I have the same issue. If i only export MMS or SMS, it will work fine. If I try to export both, it fails.

**Comment by tom93** [comment] 2024-07-07 00:27
@DaGeek247, are you getting a crash? If so, see #6 (APK with patch:
https://github.com/FossifyOrg/Messages/issues/6#issuecomment-2004587479).
If not, I have some questions: What precisely happens during the failed
import after you tap "OK"? What are the file sizes of the successful
individual SMS and MMS exports? And please check you have enough available
storage.

@QuestioningEspecialy, I just noticed that you don't get a crash (unlike
#6), and that SMS-only worked for you originally but not with my APK. So my
theory that the patch is allowing the app to progress further and encounter
the SecurityException is probably wrong. I think getting the debug logs is
the next logical step in troubleshooting (I'm happy to build a debug APK
that displays the full exception details, let me know if you're interested).

**Comment by DaGeek247** [comment] 2024-07-07 00:35
> are you getting a crash?

Nope, just a failure to write anything after creating the empty file. 

>What precisely happens during the failed import after you tap "OK"?

I press export, I select the documents folder as the save location with the default name. It then shows the little "Exporting" notification at the bottom of the screen. After 15 seconds, the settings screen switches back to the text conversations screen on it's own. The new file has no data in it.

>What are the file sizes of the successful individual SMS and MMS exports?

47.42MB for the MMS file, and 2.15MB for the SMS file.

>And please check you have enough available storage.

Oh it definitely has the space. 67GB free on the phone storage.

**Comment by tom93** [comment] 2024-07-07 07:44
@DaGeek247:

> After 15 seconds, the settings screen switches back to the text conversations screen on it's own.

That's odd. The app is supposed to stay on the Settings screen after the export finishes.
And the code should display either "Exporting successful", or an error message, or a crash dialog when the export finishes (so in all cases you should see *something*).
The only explanation I can think of is that the OS is terminating the activity.
Are you using Android or GrapheneOS? And which version?

I tried to reproduce the issue using backups of a similar size in an emulator (Android 14), but the export worked fine (and was pretty fast).
I don't know if it could be an out-of-memory issue. On the one hand, 50MB isn't that big. On the other hand, the only difference between individual SMS/MMS export and combined export should be the size (and time).
I think my APK with the out-of-memory fix (https://github.com/FossifyOrg/Messages/issues/6#issuecomment-2004587479) might still be worth a shot. Even better would be a debug build that displays more information. (And best of all would be the logcat output...)

**Comment by DaGeek247** [comment] 2024-07-07 15:39
>Are you using Android or GrapheneOS? And which version?

Android 13, OnUI 5.1, Google Play November 1, 2023, Security Patch June 1, 2024, S20FE 5G. 

The custom patched version exported successfully. The current f-droid version (1.0.1) continues to repeatably fail to export both sms and mms.

**Comment by tom93** [comment] 2024-07-08 09:29
> The custom patched version exported successfully.

Cool, so this should be fixed once #139 is merged & released.

I was mistaken about the crash dialog -- Android can silently restart the app without giving any indication that there was a crash. On Android 14, the dialog "[app] keeps stopping" is only displayed if the app crashed multiple times within a short time period; further, in my testing I couldn't make the dialog appear a second time unless I reinstalled the app.

@QuestioningEspecialy, given all this, I believe you *are* running into the same bug after all (the confirmation would be if the app switches to the conversation list after the export instead of staying on the Settings screen). So just wait until #139 is merged & released.

Also, I worked out why you got the SecurityException. You [wrote](https://github.com/FossifyOrg/Messages/issues/6#issuecomment-2105940085)

> after finding a way around setting it as the new default app just so i can open it (App info > Additional settings in the app)

At first I misread this and thought you just had some trouble making it the default messaging app, but now I realise that *you managed to open the app without making it the default messaging app*. This isn't supported, and *can't* be supported because the [Google Play policy requirements](https://support.google.com/googleplay/android-developer/answer/10208820#zippy=%2Cpermitted-uses-of-the-sms-and-call-log-permissions) say

> Apps must be actively registered as the default SMS, Phone, or Assistant handler before prompting users to accept any of SMS or Call Log permissions. Those apps must immediately stop using the permission when they're no longer the default handler.

So the "bug" is that when the app is launched using your clever workaround (App info > Additional settings in the app) it doesn't ask you to make it the default messaging app. It *should* ask you do make it the default messaging app, because otherwise it can't do anything useful (it's not supposed to request any SMS permissions due to the Google Play policy, and without permissions it will just get a SecurityException).

**Closed** 2024-12-25 13:21 UTC
Labels: bug
