### ISSUE TITLE
Error Code 5 with pic under limit

### ISSUE THREAD

**Issue by Shuggaloaf** [FossifyOrg/Messages#199] opened 2024-07-31 15:34 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung S10e

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Add an image under the limit size in settings.
2. Hit Send
3. See error

### Expected behavior

Pic is sent

### Actual behavior

Pic is not sent. Error Code 5

### Additional information

I have had the attachment limit set to 1MB and this has been working for the last week (since I 1st installed). Today I started getting this error. I also tried changing the limit to 2MB and have the same issue.

I did some testing with sending pics of varying sizes. It seems anything over 800KB does get sent. It doesn't matter what the attachment limit size is. 

To rule out a change with my carrier, other than checking online I also tried the default messaging app and Textra. Both were able to send all pics without issue. 

Because of that, and that this was working yesterday and nothing has changed (no app or phone updates, no setting changes), this is seeming like a bug. Let me know what other info can help.

**Comment by Aga-C** [comment] 2024-07-31 16:02
What is the file format of the image you are trying to send?

Also, if you weren't able to send an image with the limit set to 1 MB, changing it to 2 MB doesn't make sense. You should set it to 600 kB or even lower.

**Comment by Shuggaloaf** [comment] 2024-07-31 16:47
All images are jpg. 

I guess you're right with that but since I can send those same images with other 2 other apps I'm guessing it's not related to that anyway (Textra I have set to 2MB w/o issue).

**Comment by Aga-C** [comment] 2024-07-31 16:55
> I guess you're right with that but since I can send those same images with other 2 other apps I'm guessing it's not related to that anyway (Textra I have set to 2MB w/o issue).

Have you at least tried lowering the limit to any value lower than 1 MB? It will help us to know whether it's a problem with file size limit or something different. Textra isn't a good example here because in the other bug report it was found that Textra compresses images much below the set limit (https://github.com/FossifyOrg/Messages/issues/45#issuecomment-1909136137).

**Comment by Shuggaloaf** [comment] 2024-07-31 18:28
Ah I see, sorry I misunderstood the need for that test. I just tried 600kb and it _did_ go through. 

However something still seems off because this is what T-mobile says about their SMS limits: 

> All networks restrict the size of MMS. For T-Mobile, the max sending size is 1MB, 3 MB for receiving, and under 3072 x 3072 resolution.

The original size of the image I sent was 818kb and was well below those dimensions. I also checked with the person I sent the image to when I tested with textra and the size came through unchanged. Not saying I don't believe they would do so with larger pics, but at least with pic sizes under the 1MB limit I have set (and I guess under the carriers 1MB limit?) it seems they are not being resized. 

So I guess it boils down to (1) my carrier allows SMS >= 1MB; (2) I can send an 800kb file with Textra and it is received as 800kb (proving the network is allowing this filesize); and (3) I cannot send the same file with Fossify Messenger unless shrinking it. 

Is it possible FM is adding some kind of overhead that would kick it about the 1MB limit? (So approx 180kb)

**Comment by naveensingh** [comment] 2024-08-01 08:39
Isn't this a duplicate of https://github.com/FossifyOrg/Messages/issues/45?

We should keep 'Error code 5' in one place as it's always about the final MMS size.

**Closed** 2024-08-01 09:00 UTC
Labels: bug, needs triage

**Comment by TheRealAmeritus** [comment] 2025-12-28 16:47
I have consistently been unable to send images to a single recipient or to multiple recipients. Attached screenshots are to a singles recipient. I have "no limit" selected for MMS message size. Initial message without text, but tried to send with text since reading some of the closed past issues that has sometimes affected things. I have not denied the app any requested permissions. Under the message in red text reads "not sent. Touch to retry". Touching to retry does not actually retry either. When trying to send just an image it does nothing. When sending with text it copies only the text to the new message box. 

Additionally (I don't know if it is related but am mentioning here just in case. I will add a new error report as needed) I have been unable to open received images directly from the message app. It just opens a blank screen. I must select and then download the image first.

App version 1.7.0 installed from f-droid on pixel 7a running graphene os build number 2025121701 & 2025122501 (android 16)

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/575532b8-eebd-493b-bf0b-eb8be41728c6" width=180 />

<img alt="ignoreImageMinify" src="https://github.com/user-attachments/assets/4c9e7225-86d1-4d10-b555-c7458dd1d9d7" width=180 />

**Comment by naveensingh** [comment] 2025-12-28 16:49
> I have "no limit" selected for MMS message size.

Please select a smaller limit like 300KB or 600KB.
