### ISSUE TITLE
Phone no.

### ISSUE THREAD

**Issue by saltsoftdrink** [FossifyOrg/Messages#84] opened 2024-02-09 04:04 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Add feature if I hold on a number it should auto copy

### Why do you want this feature?

It becomes easier to save number also this feature is there in Google messages

**Comment by inson1** [comment] 2024-02-09 04:26
duplicate of https://github.com/FossifyOrg/Messages/issues/15

**Closed** 2024-02-09 05:51 UTC
Labels: feature request, needs triage
