### ISSUE TITLE
Auto export messages.

### ISSUE THREAD

**Issue by simpleguy260** [FossifyOrg/Messages#203] opened 2024-08-09 13:22 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

An option to set auto export for all messages.
Fossify Calendar and contacts does have a similiar function.

### Why do you want this feature?

It can be used as an auto-mated backup mechanism.
Who knows when your device may brick?

### Additional information

It can be implemented in similiar way as Contact's auto-export feature.

**Comment by Aga-C** [comment] 2024-08-09 14:28
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/1.

**Closed by Aga-C** 2024-08-09 14:28 UTC
Labels: feature request, needs triage
