### ISSUE TITLE
Cannot block spam message with attachment

### ISSUE THREAD

**Issue by Acdfmwaopuio** [FossifyOrg/Messages#228] opened 2024-09-22 03:45 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Lineage OS 20-20231026-NIGHTLY-polaris

### Affected device model

Xiaomi Mi MIX 2S

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1 Add an spam keyword to blocklist such as 权益
2 Send a message attach an file or picture to self number
3 You will receive this message because no keyword block

### Expected behavior

All message, with or without attachments, must be screened for blocked terms.

### Actual behavior

Any message include blocked keyword will be blocked.

### Screenshots/Screen recordings

step1
![Screenshot_20240922-110735_短信](https://github.com/user-attachments/assets/5e70a069-299d-43ba-b19d-1bd5f8e387e5)

step2 and 3
![Screenshot_20240922-110901_短信](https://github.com/user-attachments/assets/fac8a475-e184-46be-b535-86dfbeddb7e8)

### Additional information

I am alone that I cannot review bug with other phone number.

**Comment by Aga-C** [comment] 2024-09-22 05:05
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/99.

**Closed** 2024-09-22 05:05 UTC
Labels: bug, needs triage
