### ISSUE TITLE
Problem when trying to open a PDF

### ISSUE THREAD

**Issue by Atellane** [FossifyOrg/Messages#156] opened 2024-03-31 11:33 UTC
### Checklist

- [x] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

EMUI 12.0.0

### Affected device model

Huawei P30 Pro

### How did you install the app?

Google Play Store

### Steps to reproduce the bug

1. Go to any conversation
2. Send a message with a pdf attach to it
3. Open it (my phone opens it with the pdf viewer from google drive)

### Expected behavior

It should show the pdf in the pdf viewer just as it do in all other messaging app I tried (with the exact same pdf).

### Actual behavior

It opens the pdf viewer but the pdf never shows.

### Screenshots/Screen recordings

![Screenshot_20240331_132846_edit_236417747141529](https://github.com/FossifyOrg/Messages/assets/98706149/5035cc8a-fb6f-48fd-88d8-144e8472a2a4)
![Screenshot_20240331_132850_com google android apps docs_edit_236427706456632](https://github.com/FossifyOrg/Messages/assets/98706149/fc3a1a7a-b581-4d50-958d-30dfb46463a9)

### Additional information

I had the same bug with another pdf file so I assume it's not a problem about this specific file but with all pdf files.

**Comment by SilverPuppy** [comment] 2024-03-31 13:42
This is a very niche use case. While it is obviously possible to send any suitably small file over the MMS protocol, sending a PDF that way is very uncommon, and you're the first person I've known to actually do it.

Have you confirmed that the PDF is not damaged by long pressing it and saving it to open externally?

**Comment by Aga-C** [comment] 2024-03-31 14:15
I close it because despite sending PDF via MMS is a very niche use case (as mentioned above), it also seems that it's a problem not in our app, but in Google Drive. 

I've sent and received MMS with PDF and tried opening it with the following apps: MuPDF Viewer, Librera Reader, Fennec/Firefox, Collabora Office, Microsoft 365, Google Drive. Google Drive was the only one that couldn't open that PDF, others were opening it without any problems.

**Closed by Aga-C** 2024-03-31 14:15 UTC
Labels: bug, needs triage
