### ISSUE TITLE
[BUG] Subject isnt in UTF-8

### ISSUE THREAD

**Issue by inson1** [FossifyOrg/Messages#16] opened 2024-01-02 16:33 UTC
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
title

It should say "Nová zpráva od"

To be clear I'm using English (uk) as system language and this is Czech

**To Reproduce**
1. Open the app
2. See message with default text "New message from xxxxxxx" isnt in UTF-8.

**Expected behavior**
It should use UTF-8

**Screenshots**
![image](https://github.com/FossifyOrg/SMS-Messenger/assets/75314629/059da17c-5923-4e60-99a2-bb67851462bc)

**Device info (please complete the following information):**
 - Model: xiaomi redmi note 8 pro
 - OS: Android 11
 - Version: 5.19.3

**Comment by inson1** [comment] 2024-01-02 16:35
https://github.com/SimpleMobileTools/Simple-SMS-Messenger/issues/759

**Comment by naveensingh** [comment] 2024-01-02 17:34
I have a Redmi phone lying around, I'll check...

**Comment by inson1** [comment] 2024-01-02 20:05
@Aga-C no, nothing

**Comment by inson1** [comment] 2024-01-02 20:06
btw in preview it other text with á etc work normally, just the defaullt text is bad

**Comment by Aga-C** [comment] 2024-01-02 20:29
What are you doing that you see this default text on the main screen? I also can't find "Nová zpráva od" in translated strings.

**Comment by inson1** [comment] 2024-01-08 18:28
@Aga-C its not in the app I dont know if google sms app did that or the system, but when default app changed its not in utf-8, in google sms it works

I think its subject

**Comment by Aga-C** [comment] 2024-01-08 18:37
It looks like it's a strange phone-related behavior because however I tried I couldn't reproduce it. Also, this text doesn't even come from the app. 

I'll close this issue for now, but if you or someone else would provide steps how to reproduce it from the scratch or any more hints what could cause that, we can always reopen it.

**Comment by inson1** [comment] 2024-01-08 18:37
did you tried subject?

**Closed** 2024-01-08 18:37 UTC
Labels: invalid

**Comment by Aga-C** [comment] 2024-01-08 18:41
What do you mean by SMS with subject?
