### ISSUE TITLE
Auto sync between devices.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [FossifyOrg/Messages#112] opened 2024-02-20 16:02 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Allow the user to sync their messages between devices.

### Why do you want this feature?

I lose my SMS, MMS, and RCS communications when I factory reset the OS and/or switch devices.

### Additional information

It's certainly possible, with myriad implementations (per https://android.stackexchange.com/q/77520/311449) but I don't know of any exist FOSS implementations. However, I wonder how applicable they would be to this codebase anyway.

**Comment by chesio** [comment] 2024-02-20 17:30
Messages app (as all other Fossify apps) has no Internet access (*) and I cannot imagine automatic syncing that would work without it.

(*) This is a feature, not a bug.

**Comment by RokeJulianLockhart** [comment] 2024-02-20 18:09
> https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1954703047

@chesio, does a discussion of that principle exist? I'd like to vote for it to be reverted. I can audit the codebase, so I've no reason to worry about internet access.

**Comment by Aga-C** [comment] 2024-02-20 18:19
Fossify apps (and SMT before) never had Internet access, and we don't plan on adding it. If these feature requires Internet, I'll close it as out of scope for this app.

**Comment by RokeJulianLockhart** [comment] 2024-02-20 18:45
> https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1954807125

@Aga-C, then instead, perhaps https://forum.syncthing.net/t/splitting-syncthing-into-a-library-and-a-file-sharing-tool/1277/4?u=beedellrokejulianloc would be of interest? Although I suppose the native export feature can already daisy-chain in that manner anyway.

**Comment by Aga-C** [comment] 2024-02-20 18:50
@RokeJulianLockhart There is already a possibility to manually export all messages to JSON and import them.

**Comment by inson1** [comment] 2024-02-20 19:31
@RokeJulianLockhart what about automatically exporting messages? and you could save it in some folder with sync software etc., that could solve it

**Comment by RokeJulianLockhart** [comment] 2024-02-20 19:53
> https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1954919350

@inson1, I believe that what you ask about is what I have described in https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1954853390.

**Closed** 2024-02-20 20:24 UTC
Labels: feature request, needs triage

**Comment by inson1** [comment] 2024-02-20 21:29
@RokeJulianLockhart No, I think that is different
I meant that every hour messages could be saved into some folder, that could sync it with cloud/pc etc. and the app wouldnt need internet permission
the app will probably get internet permission anyway (rcs), but things with that should be really limited

**Comment by RokeJulianLockhart** [comment] 2024-02-21 00:19
> https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1955136482

Again, @inson1, that appears identical to https://github.com/FossifyOrg/Messages/issues/112#issuecomment-1955136482 — Syncthing, for instance, is a P2P synchronizer, which (to my knowledge) is able to watch an inode (for instance, a directory) and transfer out to a specified location, whether networked or local, any added content.
