### ISSUE TITLE
Option to not open links contained inside SMS to avoid phishing

### ISSUE THREAD

**Issue by e075e** [FossifyOrg/Messages#104] opened 2024-02-17 18:10 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

It would be useful to have an option that do not allow the user to open a link contained in the text of an SMS.

The only downside I am aware is that SMS link sent by search and rescue team to enable location finding will not immediately work, since you will have to copy and paste it.

### Why do you want this feature?

Nowadays, most of them are phishing that try to steal the user's data, like bank accounts

### Additional information

Honestly, I would also make it default to be on the safe side

One fraud from the news involving SMS and spoofing:

https://www.ilfattoquotidiano.it/2024/02/10/risponde-a-falso-sms-della-banca-e-perde-240mila-euro-18-indagati-per-truffa-aggravata/7441819

**Comment by Aga-C** [comment] 2024-02-17 18:22
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/46.

**Closed by Aga-C** 2024-02-17 18:22 UTC
Labels: feature request, needs triage
