### ISSUE TITLE
Display sent time

### ISSUE THREAD

**Issue by M-Demay** [FossifyOrg/Messages#198] opened 2024-07-27 23:49 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

First, thanks for your work.
Do you plan to make the sent time of messages readable in the Properties menu ? Or to make the user able to choose to display either arrival time or sent time ?
On my device at least it is unavailable (app version 1.0.1 downloaded from F-Droid on lineageos 18.1 (Android 11) jfltexx on Samsung Galaxy S4), and I am guessing it is not available at all. Maybe it is a deliberate choice ?

### Why do you want this feature?

In other apps (the ones I previously used), I found it useful for example when time was of the essence and I was not sure if the problem raised in the text message was still there. Sometimes the problem was solved between the sending and the receiving, or the situation has changed because some event happened in-between. Another situation when I find it useful is when the sender says "tomorrow" but I receive the message when I power my phone back on and I am unsure if this "tomorrow" is today or my actual tomorrow.

**Comment by Aga-C** [comment] 2024-07-28 05:20
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/56.

**Closed by Aga-C** 2024-07-28 05:20 UTC
Labels: feature request, needs triage
