### ISSUE TITLE
Group SMS Error

### ISSUE THREAD

**Issue by yusufsunetci** [FossifyOrg/Messages#144] opened 2024-03-22 13:01 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.0

### Affected Android/Custom ROM version

Android 11

### Affected device model

Xiaomi Note 8 Pro

### How did you install the app?

None

### Steps to reproduce the bug

Create a list via Fossify Contacts
Open list an click to send sms
Opens Fossify Messages
Write messages and send.
Can't send

### Expected behavior

İt must send.

### Actual behavior

When I want to create a group sms with "Fossify Messages", it gives an error. He's not forming a group.

I wanted to send messages to the lists I created with Fossify Contacts. I opened the list and send an sms. It switched to the Fossify Messages application. I wrote the message, sent it to a list immediately, scheduled another list as an advanced date and sent it. (There are 20 people on my every lists).

But the list I sent has disappeared. He came to the list a while later, but the messages were not forwarded. I checked the remaining usage from my operator, the message was not sent.

I've repeated this several times. The result is the same.

**Comment by Aga-C** [comment] 2024-03-22 16:57
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/41.

**Closed by Aga-C** 2024-03-22 16:57 UTC
Labels: bug, needs triage

**Comment by yusufsunetci** [comment] 2024-03-23 07:24
Yes, it's a duplicate of #41, I read this but it's not exactly the same. The first part is the same. I did something else different. I also brought up the topic to write about that mistake here. The second error does not exist in the other. So I've opened a new topic.
