### ISSUE TITLE
Swipe discussion to archive/unarchive

### ISSUE THREAD

**Issue by jpggithub** [FossifyOrg/Messages#129] opened 2024-03-08 08:45 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

From the list of disxussions I woud like to archive a discussion just by swiping the discussion instead of going to the menu then clicking on "Archive".

From the list of archived discussions, it would be also nice to unarchive a discussion the same way.

### Why do you want this feature?

It would be more easy to archive one or several discussions.

**Comment by Aga-C** [comment] 2024-03-08 08:50
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/25.

**Closed** 2024-03-08 08:50 UTC
Labels: feature request, needs triage
