### ISSUE TITLE
Retain Muted Notifications setting for the sender even when the conversation is deleted

### ISSUE THREAD

**Issue by rmj-maker** [FossifyOrg/Messages#252] opened 2024-11-22 05:19 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [X] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Retain Muted Notifications setting for the sender even when the conversation is deleted

### Why do you want this feature?

I occasionally house clean (delete messages) but I still want the new messages from those senders to come with muted notification. The setting is lost when you delete the conversation.

**Comment by Aga-C** [comment] 2024-11-22 06:26
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/241.

> Another request which is related to the above. Ability to mute all conversations by default but allow only a few selected to send notifications.

It's already possible. Just mute the `Received SMS` notification channel and add custom notifications to the selected conversations.

**Closed by Aga-C** 2024-11-22 06:26 UTC
Labels: feature request, needs triage
