### ISSUE TITLE
SMS Auto-delete/Retention Policy

### ISSUE THREAD

**Issue by joewood9364** [FossifyOrg/Messages#160] opened 2024-04-13 01:02 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

Please provide an option to auto-delete messages after 1/7/30//365/custom days.

### Why do you want this feature?

This option is beneficial for privacy and security as old messages can contain OTPs/banking details/personal information etc. In some areas of the world it is important for individuals to minimise their digital footprint and retention policies/auto-delete can be very useful in ensuring this.
The option would also help to keep the SMS inbox more tidy with less clutter.

**Comment by Aga-C** [comment] 2024-04-13 05:27
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/65.

**Closed by Aga-C** 2024-04-13 05:27 UTC
Labels: feature request, needs triage
