### ISSUE TITLE
App crashes every time I receive a text.

### ISSUE THREAD

**Issue by eddieofny** [FossifyOrg/Messages#120] opened 2024-02-29 02:59 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

LG K20 Plus

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

This bug occurs anytime I receive a text.

### Expected behavior

The text should come through without crashing the app.

### Actual behavior

When a text is received, the app crashes.

### Additional information

Log from LogFox:

FATAL EXCEPTION: Thread-4
Process: org.fossify.messages, PID: 28969
java.lang.UnsupportedOperationException: MmsSmsProvider does not support deletes, inserts, or updates for this URI.
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.update(ContentProviderNative.java:568)
	at android.content.ContentResolver.update(ContentResolver.java:1426)
	at x8.x.V0(SourceFile:37)
	at sb.f.b(SourceFile:292)
	at s1.w.run(SourceFile:28)
	at java.lang.Thread.run(Thread.java:761)

**Comment by Aga-C** [comment] 2024-09-20 16:20
As a bug wasn't confirmed on the newer Android versions, I close this issue because we are [dropping support for Android 7](https://github.com/orgs/FossifyOrg/discussions/241). If someone encounters this bug on at least Android 8, please let us know.

**Closed by Aga-C** 2024-09-20 16:20 UTC
Labels: device/software specific, bug, needs triage
