### ISSUE TITLE
Can't create a message group

### ISSUE THREAD

**Issue by francois-lefoulon** [FossifyOrg/Messages#170] opened 2024-05-15 13:47 UTC
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.0.1

### Affected Android/Custom ROM version

MIUI Global 14.0.10

### Affected device model

Redmi Note 10S

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1.Tap on any SMS conversation.
2. Tap the "add member" icon
3. Search a name in "Add Contact or Number" and tap the desired contact
4. Press the checkmark to create the group conversation

### Expected behavior

Create a message group to send several messages at once.

### Actual behavior

An error text shows up saying "An unknown error occured"

**Comment by Aga-C** [comment] 2024-05-15 15:02
It's a duplicate of https://github.com/FossifyOrg/Messages/issues/41.

**Closed by Aga-C** 2024-05-15 15:02 UTC
Labels: bug, needs triage
