### ISSUE TITLE
Add setting to make phone numbers clickable

### ISSUE THREAD

**Issue by m0byn** [FossifyOrg/Messages#19] opened 2024-01-07 10:33 UTC
**Checklist**
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
 - [x]  This issue contains only one feature request.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Is your feature request related to a problem? Please describe.**
So, if I miss a call by being offline my provider sends me an SMS with the missed number and some other information regarding the missed call, e.g. date, time. In most cases, I do not recognize the number. Therefore, in order to know whose call I missed, I have to enter the number into my dialer app and see which contact it is. Unfortunately, the number is not clickable, so I have to either copy the number or type it manually. Copying the number requires the following steps:

1. Long press the message
2. click 3 dots in the top right
3. click "select text"
4. select the number
5. copy to dialer app

In total, a minimum of 5 clicks is required to know which number tried to call me. In my optinion, this is not the easiest solution.  

**Describe the solution you'd like**
Would it be possible to add a setting to make phone numbers clickable? In more detail, recognize the phone numbers as links and if someone clicks the number then the dialer app should open with the number already inserted. Furthermore, if someone would like to only copy the number or send an sms, make these options available by long pressing the clickable number.

**Additional context**
I was very very surprised to hear that the SMT suit was sold to a company with no advice. Therefore, I am delighted that someone is continuing the project - keep up the good vibes!

**Comment by Aga-C** [comment] 2024-01-07 10:38
It's a duplicate of https://github.com/FossifyOrg/SMS-Messenger/issues/15.

**Closed by Aga-C** 2024-01-07 10:38 UTC
Labels: duplicate

**Comment by m0byn** [comment] 2024-01-07 10:43
Thank you for the information. In my optinion, I elaborated more concisely and precicely on what I would suggest. Is it OK if I add my suggestions to #15 in a comment?

**Comment by Aga-C** [comment] 2024-01-07 10:46
Feel free to add your notes there.
